#!/usr/bin/env python3
"""Generate complete p3-safety.js with all 118 elements' safety data.
Keeps existing 33 precise entries and adds the remaining 85."""

# Safety data for the 85 missing elements
# Format: z: dict of safety fields
# Existing elements (already in file): 1-20, 24-29, 33, 35, 37-38, 48, 51, 53

SAFETY_DATA = {
    # ── Period 4 missing ──
    21: {  # Sc 钪
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 30000–80000 / kg (Sc₂O₃)'",
        'majorMinerals': "['钪钇石 (thortveitite)','铀矿尾矿（伴生）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩（N95）、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂；粉末禁止用水'",
        'neutralizationMethod': "'清扫收集；粉末用惰性介质覆盖'",
    },
    22: {  # Ti 钛
        'ghsPictograms': "['GHS02']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228']", 'ghsPStatements': "['P210','P280']",
        'unNumber': "UN 2546 (Ti 粉末)", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '10', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 60–120 / kg (海绵钛)'",
        'majorMinerals': "['金红石 (rutile, TiO₂)','钛铁矿 (ilmenite, FeTiO₃)']",
        'ergGuide': "'ERG 135 (Ti 粉末)'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、D类灭火器；粉末禁止用水'",
        'neutralizationMethod': "'清扫收集；钛粉在惰性气氛下处理'",
    },
    23: {  # V 钒
        'ghsPictograms': "['GHS05','GHS06','GHS08','GHS09']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H301','H311','H315','H319','H332','H335','H372','H410']", 'ghsPStatements': "['P260','P280','P305+P351+P338']",
        'unNumber': "UN 3287", 'transportClass': "'6.1 (V 化合物)'",
        'ld50Oral': '970', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.05', 'oelSTEL': 'null', 'idlh': '35',
        'carcinogenicity': "'2B'",
        'pricePerKg': "'¥ 300–600 / kg (V₂O₅)'",
        'majorMinerals': "['钒钛磁铁矿','钒铅矿 (vanadinite)']",
        'ergGuide': "'ERG 154'", 'ppe': "'P100 防毒面具、防护服、手套（V₂O₅ 有毒）'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'湿法除尘；含钒废液沉淀为 V(OH)₃ 处置'",
    },
    30: {  # Zn 锌
        'ghsPictograms': "['GHS02','GHS05','GHS09']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H400','H410']", 'ghsPStatements': "['P210','P273','P280','P305+P351+P338']",
        'unNumber': "UN 1436 (Zn 粉末)", 'transportClass': "'4.3 (粉末)'",
        'ld50Oral': '630', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '5', 'oelSTEL': '10', 'idlh': '500',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 18–30 / kg (锌锭)'",
        'majorMinerals': "['闪锌矿 (sphalerite, ZnS)','菱锌矿 (smithsonite)']",
        'ergGuide': "'ERG 138 (Zn 粉)'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、D类灭火器；粉末禁止用水/泡沫'",
        'neutralizationMethod': "'清扫收集；含锌废液加碱沉淀为 Zn(OH)₂'",
    },
    31: {  # Ga 镓
        'ghsPictograms': "['GHS05','GHS06']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H302','H314','H318']", 'ghsPStatements': "['P280','P305+P351+P338','P310']",
        'unNumber': "null", 'transportClass': "'8 (Ga 化合物)'",
        'ld50Oral': '4740', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.1', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 2000–5000 / kg (金属镓)'",
        'majorMinerals': "['铝土矿（伴生 Ga 50-100 ppm）','闪锌矿（伴生）']",
        'ergGuide': "'ERG 154'", 'ppe': "'防护手套、护目镜、防酸服'",
        'firefightingAgent': "'干粉、CO₂；禁止用水'",
        'neutralizationMethod': "'用稀酸中和；Ga 在手中熔化需戴手套'",
    },
    32: {  # Ge 锗
        'ghsPictograms': "['GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H302','H315','H319','H335']", 'ghsPStatements': "['P261','P280','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.6', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 8000–15000 / kg (Ge 金属)'",
        'majorMinerals': "['锗石 (argyrodite)','闪锌矿（伴生）','煤灰']",
        'ergGuide': "'ERG 154'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Ge 废液加碱沉淀处置'",
    },
    34: {  # Se 硒
        'ghsPictograms': "['GHS06','GHS08','GHS09']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H301','H331','H373','H410']", 'ghsPStatements': "['P260','P273','P301+P310']",
        'unNumber': "UN 2658", 'transportClass': "'6.1'",
        'ld50Oral': '7', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.2', 'oelSTEL': 'null', 'idlh': '1',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 200–500 / kg (Se 金属)'",
        'majorMinerals': "['铜矿（伴生 Se）','硫矿（伴生）']",
        'ergGuide': "'ERG 154'", 'ppe': "'P100 防毒面具、防护服、手套'",
        'firefightingAgent': "'水雾、干粉、CO₂；产生 SeO₂ 有毒烟雾'",
        'neutralizationMethod': "'用亚硫酸钠还原为 Se 单质后过滤回收'",
    },
    36: {  # Kr 氪
        'ghsPictograms': "['GHS04']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H280']", 'ghsPStatements': "['P403']",
        'unNumber': "UN 1056", 'transportClass': "'2.2'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 500–1500 / kg (Kr, 高纯)'",
        'majorMinerals': "['空气 (1.14 ppm v/v)']",
        'ergGuide': "'ERG 120'", 'ppe': "'防冻手套、护目镜'",
        'firefightingAgent': "'不适用（不燃）'",
        'neutralizationMethod': "'通风扩散'",
    },
    # ── Period 5 missing ──
    39: {  # Y 钇
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '4200', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '1', 'oelSTEL': 'null', 'idlh': '500',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 100–300 / kg (Y₂O₃)'",
        'majorMinerals': "['钪钇石 (thortveitite)','独居石（伴生 Y）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Y 废液加草酸沉淀'",
    },
    40: {  # Zr 锆
        'ghsPictograms': "['GHS02']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228']", 'ghsPStatements': "['P210','P240','P280']",
        'unNumber': "UN 2008 (Zr 粉末)", 'transportClass': "'4.2 (粉末)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '5', 'oelSTEL': '10', 'idlh': '25',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 150–400 / kg (海绵锆)'",
        'majorMinerals': "['锆石 (zircon, ZrSiO₄)','斜锆石 (baddeleyite)']",
        'ergGuide': "'ERG 135 (Zr 粉)'", 'ppe': "'防尘口罩、防静电手套、护目镜'",
        'firefightingAgent': "'干砂、D类灭火器；粉末禁止用水'",
        'neutralizationMethod': "'清扫收集；粉末在惰性气氛处理'",
    },
    41: {  # Nb 铌
        'ghsPictograms': "['GHS02']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228']", 'ghsPStatements': "['P210','P280']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '5', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 300–600 / kg (铌铁)'",
        'majorMinerals': "['铌铁矿 (columbite)','烧绿石 (pyrochlore)']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干粉、CO₂；粉末用干砂'",
        'neutralizationMethod': "'清扫收集'",
    },
    42: {  # Mo 钼
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '5', 'oelSTEL': 'null', 'idlh': '5000',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 250–500 / kg (钼铁)'",
        'majorMinerals': "['辉钼矿 (molybdenite, MoS₂)']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂；粉末用干砂'",
        'neutralizationMethod': "'清扫收集；含 Mo 废液沉淀为 MoS₃'",
    },
    43: {  # Tc 锝（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS07','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H301','H315','H319','H350','H373']", 'ghsPStatements': "['P201','P280','P305+P351+P338']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核医学 ⁹⁹ᵐTc 临时配制；无商品化价格'",
        'majorMinerals': "['全部为人工合成（反应堆 ⁹⁹Mo→⁹⁹ᵐTc）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    44: {  # Ru 钌
        'ghsPictograms': "['GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H319']", 'ghsPStatements': "['P280','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '1', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 800–2000 / kg (Ru 金属)'",
        'majorMinerals': "['铂矿（伴生 Ru）','镍矿（伴生）']",
        'ergGuide': "'ERG 154'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；RuO₄ 剧毒需特殊处置'",
    },
    45: {  # Rh 铑
        'ghsPictograms': "['GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H319']", 'ghsPStatements': "['P280','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.1', 'oelSTEL': 'null', 'idlh': '100',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 300000–800000 / kg (Rh 金属)'",
        'majorMinerals': "['铂矿（伴生 Rh）','镍矿（伴生）']",
        'ergGuide': "'ERG 154'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；Rh 盐需沉淀处置'",
    },
    46: {  # Pd 钯
        'ghsPictograms': "['GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H319']", 'ghsPStatements': "['P280','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 300000–600000 / kg (Pd 金属)'",
        'majorMinerals': "['铂矿（伴生 Pd）','镍矿（伴生）']",
        'ergGuide': "'ERG 154'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；回收价值高'",
    },
    47: {  # Ag 银
        'ghsPictograms': "['GHS05','GHS09']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H319','H400','H410']", 'ghsPStatements': "['P273','P280','P305+P351+P338']",
        'unNumber': "UN 3089 (Ag 粉末)", 'transportClass': "'9'",
        'ld50Oral': '2500', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.1', 'oelSTEL': 'null', 'idlh': '10',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 7000–9000 / kg (Ag 金属)'",
        'majorMinerals': "['辉银矿 (argentite, Ag₂S)','自然银']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含银废液加 Na₂S 沉淀为 AgS 回收'",
    },
    49: {  # In 铟
        'ghsPictograms': "['GHS07','GHS08']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H302','H315','H319','H373']", 'ghsPStatements': "['P260','P280','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': '3360', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.1', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 2000–5000 / kg (In 金属)'",
        'majorMinerals': "['闪锌矿（伴生 In）','锡矿（伴生）']",
        'ergGuide': "'ERG 154'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 In 废液沉淀处置'",
    },
    50: {  # Sn 锡
        'ghsPictograms': "['GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H319','H335']", 'ghsPStatements': "['P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089 (Sn 粉末)", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '7400', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '2', 'oelSTEL': 'null', 'idlh': '100',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 150–250 / kg (锡锭)'",
        'majorMinerals': "['锡石 (cassiterite, SnO₂)']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；有机锡化合物需特殊处置'",
    },
    52: {  # Te 碲
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H301','H311','H315','H319','H332','H373']", 'ghsPStatements': "['P260','P280','P301+P310','P305+P351+P338']",
        'unNumber': "UN 3288", 'transportClass': "'6.1'",
        'ld50Oral': '83', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.1', 'oelSTEL': 'null', 'idlh': '25',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 300–800 / kg (Te 金属)'",
        'majorMinerals': "['铜矿（伴生 Te）','碲铅矿 (altaite)']",
        'ergGuide': "'ERG 154'", 'ppe': "'P100 防毒面具、防护服、手套'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'湿法除尘；含 Te 废液还原为 Te 单质回收'",
    },
    54: {  # Xe 氙
        'ghsPictograms': "['GHS04']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H280']", 'ghsPStatements': "['P403']",
        'unNumber': "UN 2036", 'transportClass': "'2.2'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 200000–500000 / kg (Xe, 高纯)'",
        'majorMinerals': "['空气 (0.087 ppm v/v)']",
        'ergGuide': "'ERG 120'", 'ppe': "'防冻手套、护目镜'",
        'firefightingAgent': "'不适用（不燃）'",
        'neutralizationMethod': "'通风扩散'",
    },
    # ── Period 6 missing ──
    55: {  # Cs 铯
        'ghsPictograms': "['GHS02','GHS05']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H228','H260','H314']", 'ghsPStatements': "['P210','P223','P280','P305+P351+P338']",
        'unNumber': "UN 1407", 'transportClass': "'4.3'",
        'ld50Oral': '2600', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 5000–20000 / kg (Cs 金属)'",
        'majorMinerals': "['铯榴石 (pollucite)','锂云母（伴生 Cs）']",
        'ergGuide': "'ERG 138'", 'ppe': "'防火防毒手套、面罩、防碱防护服'",
        'firefightingAgent': "'干砂、D类灭火器；禁止用水'",
        'neutralizationMethod': "'用干砂覆盖；生成 CsOH 用稀酸中和'",
    },
    56: {  # Ba 钡
        'ghsPictograms': "['GHS02','GHS05']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H228','H260','H314']", 'ghsPStatements': "['P210','P223','P280','P305+P351+P338']",
        'unNumber': "UN 1400", 'transportClass': "'4.3'",
        'ld50Oral': '118', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.5', 'oelSTEL': 'null', 'idlh': '50',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 80–200 / kg (BaCO₃)'",
        'majorMinerals': "['重晶石 (barite, BaSO₄)','毒重石 (witherite, BaCO₃)']",
        'ergGuide': "'ERG 138'", 'ppe': "'防火防毒手套、面罩、防碱防护服'",
        'firefightingAgent': "'干砂、D类灭火器；禁止用水'",
        'neutralizationMethod': "'用干砂覆盖；可溶性钡盐用硫酸钠沉淀为 BaSO₄'",
    },
    57: {  # La 镧
        'ghsPictograms': "['GHS02','GHS05','GHS07']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H228','H260','H315','H319','H335']", 'ghsPStatements': "['P210','P223','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.3 (粉末)'",
        'ld50Oral': '4200', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 50–150 / kg (La₂O₃)'",
        'majorMinerals': "['独居石 (monazite)','氟碳铈矿 (bastnäsite)']",
        'ergGuide': "'ERG 138'", 'ppe': "'防火防毒手套、面罩、防尘口罩'",
        'firefightingAgent': "'干砂、D类灭火器；禁止用水'",
        'neutralizationMethod': "'用干砂覆盖；生成 La(OH)₃ 用稀酸中和'",
    },
    58: {  # Ce 铈
        'ghsPictograms': "['GHS02','GHS05','GHS07']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H228','H260','H315','H319','H335']", 'ghsPStatements': "['P210','P223','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.3 (粉末)'",
        'ld50Oral': '2104', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 40–100 / kg (CeO₂)'",
        'majorMinerals': "['氟碳铈矿 (bastnäsite)','独居石 (monazite)']",
        'ergGuide': "'ERG 138'", 'ppe': "'防火防毒手套、面罩、防尘口罩'",
        'firefightingAgent': "'干砂、D类灭火器；禁止用水'",
        'neutralizationMethod': "'用干砂覆盖；铈粉可自燃需惰性气氛保护'",
    },
    59: {  # Pr 镨
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '4500', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 80–200 / kg (Pr₆O₁₁)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Pr）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Pr 废液加草酸沉淀'",
    },
    60: {  # Nd 钕
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 50–150 / kg (Nd₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Nd）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Nd 废液加草酸沉淀'",
    },
    61: {  # Pm 钷（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H301','H315','H319','H350','H373']", 'ghsPStatements': "['P201','P280','P305+P351+P338']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核反应堆副产物；无商品化价格'",
        'majorMinerals': "['全部为人工合成（反应堆产物）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    62: {  # Sm 钐
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 80–200 / kg (Sm₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Sm）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Sm 废液加草酸沉淀'",
    },
    63: {  # Eu 铕
        'ghsPictograms': "['GHS02','GHS05','GHS07']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H228','H260','H315','H319','H335']", 'ghsPStatements': "['P210','P223','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.3 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 500–2000 / kg (Eu₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Eu）']",
        'ergGuide': "'ERG 138'", 'ppe': "'防火防毒手套、面罩、防尘口罩'",
        'firefightingAgent': "'干砂、D类灭火器；禁止用水'",
        'neutralizationMethod': "'用干砂覆盖；铕粉可自燃'",
    },
    64: {  # Gd 钆
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 80–200 / kg (Gd₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Gd）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Gd 废液加草酸沉淀'",
    },
    65: {  # Tb 铽
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 300–800 / kg (Tb₄O₇)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Tb）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Tb 废液加草酸沉淀'",
    },
    66: {  # Dy 镝
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 200–600 / kg (Dy₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Dy）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Dy 废液加草酸沉淀'",
    },
    67: {  # Ho 钬
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 300–800 / kg (Ho₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Ho）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Ho 废液加草酸沉淀'",
    },
    68: {  # Er 铒
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 200–500 / kg (Er₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Er）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Er 废液加草酸沉淀'",
    },
    69: {  # Tm 铥
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 500–2000 / kg (Tm₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Tm）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Tm 废液加草酸沉淀'",
    },
    70: {  # Yb 镱
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 100–300 / kg (Yb₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Yb）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Yb 废液加草酸沉淀'",
    },
    71: {  # Lu 镥
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 500–2000 / kg (Lu₂O₃)'",
        'majorMinerals': "['独居石','氟碳铈矿（伴生 Lu）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Lu 废液加草酸沉淀'",
    },
    72: {  # Hf 铪
        'ghsPictograms': "['GHS02','GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228','H315','H319','H335']", 'ghsPStatements': "['P210','P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.5', 'oelSTEL': 'null', 'idlh': '50',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 500–2000 / kg (Hf 金属)'",
        'majorMinerals': "['锆石（伴生 Hf 1-3%）']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂；粉末禁止用水'",
        'neutralizationMethod': "'清扫收集；Hf 粉末在惰性气氛处理'",
    },
    73: {  # Ta 钽
        'ghsPictograms': "['GHS02']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H228']", 'ghsPStatements': "['P210','P280']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '5', 'oelSTEL': 'null', 'idlh': '2500',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 200–500 / kg (Ta₂O₅)'",
        'majorMinerals': "['钽铁矿 (tantalite)','铌钽矿 (coltan)']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'干砂、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；Ta 生物惰性高'",
    },
    74: {  # W 钨
        'ghsPictograms': "['GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H319','H335']", 'ghsPStatements': "['P261','P280','P305+P351+P338']",
        'unNumber': "UN 3089", 'transportClass': "'4.1 (粉末)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '5', 'oelSTEL': '10', 'idlh': '500',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 250–500 / kg (钨铁)'",
        'majorMinerals': "['黑钨矿 (wolframite)','白钨矿 (scheelite)']",
        'ergGuide': "'ERG 133'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集'",
    },
    75: {  # Re 铼
        'ghsPictograms': "['GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H319','H335']", 'ghsPStatements': "['P261','P280','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 5000–15000 / kg (Re 金属)'",
        'majorMinerals': "['辉钼矿（伴生 Re 0.01-0.2%）','铜矿（伴生）']",
        'ergGuide': "'ERG 154'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集'",
    },
    76: {  # Os 锇
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H315','H318','H350']", 'ghsPStatements': "['P260','P280','P284','P301+P310']",
        'unNumber': "UN 3089", 'transportClass': "'6.1'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.0002', 'oelSTEL': '0.0006', 'idlh': '0.001',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 50000–200000 / kg (Os 金属)'",
        'majorMinerals': "['铂矿（伴生 Os）','铱锇矿']",
        'ergGuide': "'ERG 154'", 'ppe': "'供气式呼吸器（SCBA）、防化服、双层手套（OsO₄ 剧毒）'",
        'firefightingAgent': "'干粉、CO₂；OsO₄ 蒸气剧毒需 SCBA'",
        'neutralizationMethod': "'OsO₄ 用碱液（NaOH）吸收还原；危险废物专业处置'",
    },
    77: {  # Ir 铱
        'ghsPictograms': "['GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H319']", 'ghsPStatements': "['P280','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 100000–300000 / kg (Ir 金属)'",
        'majorMinerals': "['铂矿（伴生 Ir）','铱锇矿']",
        'ergGuide': "'ERG 154'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；Ir 化合物需沉淀处置'",
    },
    78: {  # Pt 铂
        'ghsPictograms': "['GHS07','GHS08']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H317','H319','H334']", 'ghsPStatements': "['P261','P280','P285','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.002', 'oelSTEL': 'null', 'idlh': '4',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 250000–350000 / kg (Pt 金属)'",
        'majorMinerals': "['铂矿 (platinum ore)','镍矿（伴生 Pt）']",
        'ergGuide': "'ERG 154'", 'ppe': "'防尘口罩、手套、护目镜（Pt 盐可致敏）'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；Pt 盐溶液用锌粉还原回收'",
    },
    79: {  # Au 金
        'ghsPictograms': "['GHS07','GHS09']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H315','H319','H413']", 'ghsPStatements': "['P273','P280','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 45000000–55000000 / kg (Au 金属)'",
        'majorMinerals': "['自然金','黄铁矿（伴生 Au）','铜矿（伴生）']",
        'ergGuide': "null", 'ppe': "'手套、护目镜'",
        'firefightingAgent': "'不适用（不燃）'",
        'neutralizationMethod': "'清扫收集；金盐废液回收价值高'",
    },
    80: {  # Hg 汞
        'ghsPictograms': "['GHS05','GHS06','GHS08','GHS09']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H373','H410']", 'ghsPStatements': "['P260','P273','P280','P284','P301+P310']",
        'unNumber': "UN 2809", 'transportClass': "'8'",
        'ld50Oral': '1', 'ld50Dermal': 'null', 'lc50Inhalation': '0.029',
        'oelTWA': '0.025', 'oelSTEL': 'null', 'idlh': '10',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 2000–5000 / kg (汞)'",
        'majorMinerals': "['辰砂 (cinnabar, HgS)']",
        'ergGuide': "'ERG 156'", 'ppe': "'供气式呼吸器、防化服、耐汞手套'",
        'firefightingAgent': "'切断汞源；用硫粉覆盖汞珠使其生成 HgS；禁用高压水'",
        'neutralizationMethod': "'汞泄漏用硫粉或锌粉覆盖生成不挥发硫化物/汞齐；危险废物专业处置'",
    },
    81: {  # Tl 铊
        'ghsPictograms': "['GHS05','GHS06','GHS08','GHS09']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H373','H410']", 'ghsPStatements': "['P260','P273','P280','P284','P301+P310']",
        'unNumber': "UN 3288", 'transportClass': "'6.1'",
        'ld50Oral': '15', 'ld50Dermal': 'null', 'lc50Inhalation': '0.02',
        'oelTWA': '0.1', 'oelSTEL': 'null', 'idlh': '15',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 500–2000 / kg (Tl 金属)'",
        'majorMinerals': "['铜矿（伴生 Tl）','铅锌矿（伴生）']",
        'ergGuide': "'ERG 154'", 'ppe': "'供气式呼吸器、A级防化服、双层手套（Tl 剧毒）'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'含铊废液加 Na₂S 沉淀为 Tl₂S 或用活性炭吸附'",
    },
    82: {  # Pb 铅
        'ghsPictograms': "['GHS05','GHS07','GHS08','GHS09']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H302','H332','H351','H360','H372','H410']", 'ghsPStatements': "['P201','P260','P280','P301+P310+P330']",
        'unNumber': "UN 3089 (Pb 粉末)", 'transportClass': "'6.1 (粉末)'",
        'ld50Oral': '500', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.05', 'oelSTEL': 'null', 'idlh': '100',
        'carcinogenicity': "'2A'",
        'pricePerKg': "'¥ 12–20 / kg (铅锭)'",
        'majorMinerals': "['方铅矿 (galena, PbS)','白铅矿 (cerussite)']",
        'ergGuide': "'ERG 154'", 'ppe': "'P100 防毒面具、防护服、手套（Pb 及化合物 2A 类致癌）'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'含铅废液加 Na₂CO₃ 或 Na₂S 沉淀为 PbCO₃/PbS 处置'",
    },
    83: {  # Bi 铋
        'ghsPictograms': "['GHS07']", 'ghsSignal': "'Warning'",
        'ghsHStatements': "['H302','H315','H319','H335']", 'ghsPStatements': "['P261','P280','P305+P351+P338']",
        'unNumber': "null", 'transportClass': 'null',
        'ld50Oral': '5000', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'0'",
        'pricePerKg': "'¥ 60–150 / kg (Bi 金属)'",
        'majorMinerals': "['辉铋矿 (bismuthinite, Bi₂S₃)','铅矿（伴生 Bi）']",
        'ergGuide': "'ERG 154'", 'ppe': "'防尘口罩、手套、护目镜'",
        'firefightingAgent': "'水、干粉、CO₂'",
        'neutralizationMethod': "'清扫收集；含 Bi 废液加碱沉淀为 Bi(OH)₃'",
    },
    84: {  # Po 钋（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': '0.001', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核材料管控；无公开价格'",
        'majorMinerals': "['铀矿（伴生 Po，²¹⁰Po）','全部为反应堆产物']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    85: {  # At 砹（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核反应堆/加速器产物；无商品化价格'",
        'majorMinerals': "['全部为人工合成（加速器 ²¹⁰At）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    86: {  # Rn 氡（放射性）
        'ghsPictograms': "['GHS04','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H280','H350','H373']", 'ghsPStatements': "['P201','P260','P403']",
        'unNumber': "UN 1006", 'transportClass': "'7 (放射性气体)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'天然放射性气体；无商品化价格'",
        'majorMinerals': "['铀矿衰变产物（²³⁸U→²²⁶Ra→²²²Rn）','土壤/地下水']",
        'ergGuide': "'ERG 167'", 'ppe': "'辐射防护服、剂量计、通风设备'",
        'firefightingAgent': "'不适用（不燃）；加强通风排除 Rn'",
        'neutralizationMethod': "'通风排除；活性炭吸附；密封地下空间防渗'",
    },
    # ── Period 7 (Actinides + Superheavy) ──
    87: {  # Fr 钫（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'全部为人工合成（²²³Fr，t½=22 min）；无价格'",
        'majorMinerals': "['全部为人工合成（²²⁷Ac 衰变产物）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    88: {  # Ra 镭（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核材料管控；无公开价格'",
        'majorMinerals': "['铀矿（伴生 Ra，²²⁶Ra）','沥青铀矿']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    89: {  # Ac 锕（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核材料管控；无公开价格'",
        'majorMinerals': "['铀矿（伴生 Ac）','人工合成（²²⁷Ac）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    90: {  # Th 钍（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08','GHS09']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H301','H311','H331','H350','H373','H410']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'¥ 200–500 / kg (ThO₂)'",
        'majorMinerals': "['独居石 (monazite)','钍矿 (thorianite, ThO₂)']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    91: {  # Pa 镤（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核材料管控；无公开价格'",
        'majorMinerals': "['铀矿（伴生 Pa，²³¹Pa）','沥青铀矿']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    92: {  # U 铀（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08','GHS09']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H330','H350','H373','H410']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2979", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': '0.2', 'oelSTEL': '0.6', 'idlh': '10',
        'carcinogenicity': "'1'",
        'pricePerKg': "'¥ 200–500 / kg (U₃O₈ 黄饼)'",
        'majorMinerals': "['沥青铀矿 (uraninite, UO₂)','钒钾铀矿 (carnotite)']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套（U 及化合物 1 类致癌）'",
        'firefightingAgent': "'按放射性物质专项应急预案；注意 UF₆ 与水剧烈反应'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）；UF₆ 泄漏用碱液吸收'",
    },
    93: {  # Np 镎（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08','GHS09']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373','H410']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核反应堆产物；无商品化价格'",
        'majorMinerals': "['铀矿（极微量伴生 Np）','反应堆产物（²³⁹Np→²³⁹Pu）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    94: {  # Pu 钚（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08','GHS09']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373','H410']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核材料严格管控；无公开价格'",
        'majorMinerals': "['全部为人工合成（反应堆 ²³⁹Pu）','铀矿（极微量天然 Pu）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套（Pu 极毒）'",
        'firefightingAgent': "'按放射性物质专项应急预案；Pu 金属可自燃需惰性气氛'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    95: {  # Am 镅（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核反应堆产物；约 ¥ 1000000+ / kg (²⁴¹Am)'",
        'majorMinerals': "['全部为人工合成（反应堆 ²⁴¹Am）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    96: {  # Cm 锔（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核反应堆/加速器产物；无商品化价格'",
        'majorMinerals': "['全部为人工合成（反应堆 ²⁴²Cm/²⁴⁴Cm）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    97: {  # Bk 锫（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'加速器产物；无商品化价格'",
        'majorMinerals': "['全部为人工合成（加速器 ²⁴⁹Bk）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    98: {  # Cf 锎（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'加速器产物；约 ¥ 100000000000+ / kg (²⁵²Cf, 全球最贵物质之一)'",
        'majorMinerals': "['全部为人工合成（反应堆 ²⁵²Cf）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套（强中子源）'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    99: {  # Es 锿（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核爆/加速器产物；无商品化价格'",
        'majorMinerals': "['全部为人工合成（核爆 ²⁵³Es）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    100: {  # Fm 镄（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'核爆/加速器产物；无商品化价格'",
        'majorMinerals': "['全部为人工合成（核爆 ²⁵⁵Fm）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    101: {  # Md 钔（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'加速器产物；无商品化价格'",
        'majorMinerals': "['全部为人工合成（加速器 ²⁵⁶Md）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    102: {  # No 锘（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'加速器产物；无商品化价格'",
        'majorMinerals': "['全部为人工合成（加速器 ²⁵⁹No）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
    103: {  # Lr 铹（放射性）
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': "'加速器产物；无商品化价格'",
        'majorMinerals': "['全部为人工合成（加速器 ²⁶²Lr）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    },
}

# Superheavy elements 104-118: all radioactive, short half-lives, same template
SUPERHEAVY_INFO = {
    104: ('Rf', '𬬻'), 105: ('Db', '𬭊'), 106: ('Sg', '𬭳'), 107: ('Bh', '𬭛'),
    108: ('Hs', '𬭶'), 109: ('Mt', '鿏'), 110: ('Ds', '𫟼'), 111: ('Rg', '𬬭'),
    112: ('Cn', '鎶'), 113: ('Nh', '鉨'), 114: ('Fl', '𫓧'), 115: ('Mc', '镆'),
    116: ('Lv', '𫟷'), 117: ('Ts', '鿬'), 118: ('Og', '鿫'),
}

for z, (sym, cn) in SUPERHEAVY_INFO.items():
    SAFETY_DATA[z] = {
        'ghsPictograms': "['GHS05','GHS06','GHS08']", 'ghsSignal': "'Danger'",
        'ghsHStatements': "['H300','H310','H330','H350','H373']", 'ghsPStatements': "['P201','P260','P280','P284']",
        'unNumber': "UN 2910", 'transportClass': "'7 (放射性)'",
        'ld50Oral': 'null', 'ld50Dermal': 'null', 'lc50Inhalation': 'null',
        'oelTWA': 'null', 'oelSTEL': 'null', 'idlh': 'null',
        'carcinogenicity': "'1'",
        'pricePerKg': f"'加速器产物；{cn}({sym}) 半衰期极短，无商品化价格'",
        'majorMinerals': f"['全部为人工合成（加速器合成 {sym}）']",
        'ergGuide': "'ERG 161'", 'ppe': "'辐射防护服、供气式呼吸器、剂量计、双层手套'",
        'firefightingAgent': "'按放射性物质专项应急预案'",
        'neutralizationMethod': "'放射性废物专业处置（专用设施）'",
    }


def generate_js_entries():
    """Generate JS code for the new safety entries."""
    symbols = {
        21:'Sc',22:'Ti',23:'V',30:'Zn',31:'Ga',32:'Ge',34:'Se',36:'Kr',
        39:'Y',40:'Zr',41:'Nb',42:'Mo',43:'Tc',44:'Ru',45:'Rh',46:'Pd',47:'Ag',
        49:'In',50:'Sn',52:'Te',54:'Xe',
        55:'Cs',56:'Ba',57:'La',58:'Ce',59:'Pr',60:'Nd',61:'Pm',62:'Sm',63:'Eu',
        64:'Gd',65:'Tb',66:'Dy',67:'Ho',68:'Er',69:'Tm',70:'Yb',71:'Lu',
        72:'Hf',73:'Ta',74:'W',75:'Re',76:'Os',77:'Ir',78:'Pt',79:'Au',80:'Hg',
        81:'Tl',82:'Pb',83:'Bi',84:'Po',85:'At',86:'Rn',
        87:'Fr',88:'Ra',89:'Ac',90:'Th',91:'Pa',92:'U',93:'Np',94:'Pu',95:'Am',
        96:'Cm',97:'Bk',98:'Cf',99:'Es',100:'Fm',101:'Md',102:'No',103:'Lr',
        104:'Rf',105:'Db',106:'Sg',107:'Bh',108:'Hs',109:'Mt',110:'Ds',111:'Rg',
        112:'Cn',113:'Nh',114:'Fl',115:'Mc',116:'Lv',117:'Ts',118:'Og',
    }

    lines = []
    lines.append("")
    lines.append("// ══════════════════════════════════════════════════════")
    lines.append("//  补充元素安全数据（z=21-118 中缺失的精确数据）")
    lines.append("// ══════════════════════════════════════════════════════")
    lines.append("")

    # Sort by z
    for z in sorted(SAFETY_DATA.keys()):
        d = SAFETY_DATA[z]
        sym = symbols.get(z, '?')
        lines.append(f"P3_SAFETY[{z}] = {{  // {sym}")
        lines.append(f"  ghsPictograms: {d['ghsPictograms']},")
        lines.append(f"  ghsSignal: {d['ghsSignal']},")
        lines.append(f"  ghsHStatements: {d['ghsHStatements']},")
        lines.append(f"  ghsPStatements: {d['ghsPStatements']},")
        lines.append(f"  unNumber: {d['unNumber']},")
        lines.append(f"  transportClass: {d['transportClass']},")
        lines.append(f"  ld50Oral: {d['ld50Oral']},")
        lines.append(f"  ld50Dermal: {d['ld50Dermal']},")
        lines.append(f"  lc50Inhalation: {d['lc50Inhalation']},")
        lines.append(f"  oelTWA: {d['oelTWA']},")
        lines.append(f"  oelSTEL: {d['oelSTEL']},")
        lines.append(f"  idlh: {d['idlh']},")
        lines.append(f"  carcinogenicity: {d['carcinogenicity']},")
        lines.append(f"  pricePerKg: {d['pricePerKg']},")
        lines.append(f"  majorMinerals: {d['majorMinerals']},")
        lines.append(f"  ergGuide: {d['ergGuide']},")
        lines.append(f"  ppe: {d['ppe']},")
        lines.append(f"  firefightingAgent: {d['firefightingAgent']},")
        lines.append(f"  neutralizationMethod: {d['neutralizationMethod']},")
        lines.append("};")
        lines.append("")

    return '\n'.join(lines)


if __name__ == '__main__':
    # Read existing file
    file_path = r'E:\Desktop\periodic-table\data\p3-safety.js'
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find the insertion point (before the "合并 P3_SAFETY" comment)
    marker = "// ══════════════════════════════════════════════════════\n//  为其余 118-z 元素填充默认 P3 数据"
    if marker not in content:
        # Try alternate marker
        marker = "// ══════════════════════════════════════════════════════\n//  为其余"

    if marker in content:
        # Insert new entries before the merge function section
        new_entries = generate_js_entries()
        content = content.replace(marker, new_entries + "\n" + marker)
    else:
        print("WARNING: Could not find insertion marker!")
        # Try to find mergeP3Data function
        idx = content.find('function mergeP3Data')
        if idx > 0:
            new_entries = generate_js_entries()
            # Find the comment block before mergeP3Data
            comment_start = content.rfind('// ══', 0, idx)
            if comment_start > 0:
                content = content[:comment_start] + new_entries + "\n" + content[comment_start:]
            else:
                content = content[:idx] + new_entries + "\n" + content[idx:]

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Updated {file_path}")
    print(f"Added {len(SAFETY_DATA)} new element entries")

    # Verify all 118 are now covered
    # Count P3_SAFETY entries in the file
    import re
    entries = re.findall(r'P3_SAFETY\[\d+\]', content)
    print(f"Total P3_SAFETY entries in file: {len(entries)}")
    missing = [z for z in range(1, 119) if f'P3_SAFETY[{z}]' not in content]
    if missing:
        print(f"Still missing: {missing}")
    else:
        print("All 118 elements now have precise P3 safety data!")
